In [1]:
import pandas as pd
import os

print("Files in raw folder:", os.listdir('../data/raw/'))

movies = pd.read_csv('../data/raw/movies.csv')
ratings = pd.read_csv('../data/raw/ratings.csv')

print("\n--- Movies Data ---")
display(movies.head())

print("\n--- Ratings Data ---")
display(ratings.head())

Files in raw folder: ['movies.csv', 'ratings.csv']

--- Movies Data ---

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

--- Ratings Data ---

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [2]:
# 1. نشوفو معلومات الداتا (واش كاين قيم فارغة NaN)
print("--- Movies Info ---")
movies.info()

print("\n--- Ratings Info ---")
ratings.info()

# 2. نحسبو شحال من قيمة فارغة في كل عمود
print("\n--- Missing Values in Movies ---")
print(movies.isnull().sum())

print("\n--- Missing Values in Ratings ---")
print(ratings.isnull().sum())

--- Movies Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10329 entries, 0 to 10328
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  10329 non-null  int64
 1   title    10329 non-null  object
 2   genres   10329 non-null  object
dtypes: int64(1), object(2)
memory usage: 242.2+ KB

--- Ratings Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105339 entries, 0 to 105338
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     105339 non-null  int64
 1   movieId    105339 non-null  int64
 2   rating     105339 non-null  float64
 3   timestamp  105339 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.2 MB

--- Missing Values in Movies ---
movieId    0
title      0
genres     0
dtype: int64

--- Missing Values in Ratings ---
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64